<?php

/**
 * @file
 * Provides a Govspeak input filter.
 */

/**
 * Implements hook_help().
 */
function govspeak_help($path, $arg) {
  switch ($path) {
    case 'admin/help#govspeak':
      return t('<p>The govspeak filter allows you to enter content using <a href="https://github.com/alphagov/govspeak">Govspeak</a>, a simple plain-text syntax that is transformed into valid XHTML.</p>');
  }
}

/**
 *
 *
 * Implements hook_filter_info().
 */
function govspeak_filter_info() {
  $filters['filter_govspeak'] = array(
    'title' => t('Govspeak'),
    'description' => t('Allows content to be submitted using govspeak, a simple plain-text syntax that is filtered into valid XHTML.'),
    'process callback' => '_filter_govspeak',
    'settings callback' => '_filter_govspeak_settings',
    'tips callback'  => '_filter_govspeak_tips',
  );

  return $filters;
}

/**
 * Returns the govspeak input filter tips.
 * @TODO: make it easier for translators.
 */
function _filter_govspeak_tips($format, $long = FALSE) {
  if ($long) {
    return t('Quick Tips:<ul>
      <li>Two or more spaces at a line\'s end = Line break</li>
      <li>Double returns = Paragraph</li>
      <li>*Single asterisks* or _single underscores_ = <em>Emphasis</em></li>
      <li>**Double** or __double__ = <strong>Strong</strong></li>
      <li>This is [a link](http://the.link.example.com "The optional title text")</li>
      </ul>For complete details on the Govspeak and Markdown syntax, see the <a href="https://github.com/alphagov/govspeak">Govspeak documentation</a> and <a href="http://daringfireball.net/projects/govspeak/syntax">Markdown documentation');
  }
  else {
    return t('You can use <a href="@filter_tips">govspeak syntax</a> to format and style the text. Also see <a href="@govspeak_extra">govspeak Extra</a> for tables, footnotes, and more.', array('@filter_tips' => url('filter/tips'), '@govspeak_extra' => 'https://github.com/alphagov/govspeak'));
  }
}

/**
 * Implements hook_block_view().
 */
function govspeak_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'govspeak_help':
      $block['title'] = t('govspeak filter tips');
      $block['content'] = _govspeak_help_block();
      break;
  }

  return $block;
}

/**
 * Implements hook_block_info().
 */
function govspeak_block_info() {
  $blocks = array();
  $blocks['govspeak_help'] = array(
    'info' => t('govspeak filter tips'),
  );

  return $blocks;
}

/**
 * Provides content for the govspeak help block.
 */
function _govspeak_help_block() {
  return '<pre>' . t("
## Header 2 ##
### Header 3 ###
#### Header 4 ####
##### Header 5 #####
(Hashes on right are optional)

Link [GOV.UK](http://www.gov.uk)

Inline markup like _italics_,
 **bold**, and `code()`.

> Blockquote. Like email replies
>> And, they can be nested

* Bullet lists are easy too
- Another one
+ Another one

1. A numbered list
2. Which is numbered
3. With periods and a space

And now some code:
    // Code is indented text
    is_easy() to_remember();") . '</pre>';
}

/**
 * Filter process callback.
 */
function _filter_govspeak($text, $format) {
  if (!empty($text)) {
    module_load_include('php', 'govspeak');
    $text = govspeak($text);
  }

  return $text;
}

/**
 * Filter settings callback. Just provides a version overview.
 */
function _filter_govspeak_settings($form, &$form_state, $filter, $format, $defaults) {
  module_load_include('php', 'govspeak');

  $settings['govspeak_wrapper'] = array(
    '#type' => 'fieldset',
    '#title' => t('govspeak'),
  );
  $links = array(
    'Markdown PHP Version: <a href="http://michelf.com/projects/php-markdown/">' . MARKDOWN_VERSION . '</a>',
    'Markdown Extra Version: <a href="http://michelf.com/projects/php-markdown/">' . MARKDOWNEXTRA_VERSION . '</a>',
  );
  $settings['govspeak_wrapper']['govspeak_status'] = array(
    '#title' => t('Versions'),
    '#type' => 'item',
    '#markup' => theme('item_list', array('items' => $links)),
  );

  return $settings;
}
